### ISSUE TITLE
[Improvement] Allow to use ERC-20 token (USDC) to pay fees

### ISSUE THREAD

**Issue by JagoFigueroa** [5afe/account-abstraction-demo-ui#6]
I think it would be a nice to have to allow paying the fees of the safe creation with USDC in addition to the native token of every chain. Note that we might want to add the balance for it as well so that it is reflected on the interface:

![Screenshot 2023-03-06 at 13 23 49](https://user-images.githubusercontent.com/92332710/223109577-d9963d4e-385b-4b3d-9121-a95fc42ed44d.png)

**Comment by kamalbuilds** [comment]
I support this , do we have any updates for this ?
